# ----- Properties -----

spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      uri: mongodb://localhost:27017/lelikbjmak
      database: stock-exchange
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/stock-exchange
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver